name: ci_crash_repro
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0-88.0.dev

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  build_runner: ^2.6.1
  lints: ^6.0.0
  test: ^1.25.6
